name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build --target build -t public-dao-api ./public-dao-api
      - name: Run container tests
        run: docker run public-dao-api npm test
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '20'
      # - name: Install dependencies
      #   run: npm install
      #   working-directory: public-dao-api
      # - name: Run tests
      #   run: npm test
      #   working-directory: public-dao-api